### ISSUE TITLE
TypeError: e[0].$setDirty is not a function

### ISSUE THREAD

**Issue by xskid** [ruhley/angular-color-picker#31]
Hello,

When I'm exploring the colors it is retreiving "TypeError: e[0].$setDirty is not a function" many times I move arround pallete.

Thanks

**Comment by ruhley** [comment]
Are you able to give me some more information? Your browser version and operating system. A [codepen](http://codepen.io/) would go a long way to helping me. I am unable to replicate the issue.

**Comment by xskid** [comment]
Sure.
Angular 1.3, WIN7, Chrome (latest version)

**Comment by ruhley** [comment]
Are you by chance using AngularJS v1.3.3 or less? ```$setDirty``` was only introduced in AngularJS v1.4.4 - [changelog](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#features-23). Fixed in commit 276f9fa450158396b2cb0894377d99c709f9082e and released in [v0.6.9](https://github.com/ruhley/angular-color-picker/releases/tag/v0.6.9)
