### ISSUE TITLE
Strange interaction with Bootstrap navbar / dropdown menu

### ISSUE THREAD

**Issue by jeffricks** [ruhley/angular-color-picker#35]
Hi,

I discovered a strange issue where removing a color-picker from a page somehow disables bootstrap dropdown menus.  I've reproduced in simple form in this Plunker:

http://plnkr.co/edit/OUvnsyHTTSYf7uJP1DhU?p=preview

Reproduction Steps:

1) Click the nav dropdown menu to ensure it's working
2) Click the Remove button to remove one of the pickers
    from the page
3) Click the nav dropdown again and observe that it no
    longer expands

Thanks in advance for your attention.

-Jeff

**Comment by ruhley** [comment]
Fixed in a53fdb04d247d19d53f1f26c0bb8b3b45e6350d2 and release in [v0.6.10](https://github.com/ruhley/angular-color-picker/releases/tag/v0.6.10).

If you are interested in what caused the problem look at the old code at [Line 440](https://github.com/ruhley/angular-color-picker/blob/v0.6.9/angularjs-color-picker.js#L440) where when the directive was removed, I removed all document click events. This would have removed the bootstrap events and caused the navbar to not work. [Now](https://github.com/ruhley/angular-color-picker/blob/master/angularjs-color-picker.js#L442) I pass the function to be removed and the navbar still works.

Thanks for the great plnkr to get me started! :+1:

**Comment by jeffricks** [comment]
Thank you for the amazingly fast turnaround... the fix worked great!

-Jeff
