### ISSUE TITLE
onchange event is not firing after drag&drop

### ISSUE THREAD

**Issue by VladaSmautilus** [ruhley/angular-color-picker#48]
Hi Ruhley, 
when you select color via drag&drop, event is fired. But after that when you just click to select color, it is not. I think, that problem is in first if statement in mouseUp function.
Bye, Vlada

**Comment by ruhley** [comment]
I can confirm that the first click after drag does not fire the on change function.

Thanks for the pick up :+1:

**Comment by ruhley** [comment]
It was actually the order of the mouse events. The click was triggered after onChange, so it actually sent the previous value for click events. This also caused the problem of no onChange of the first click after a drag. 

Fixed in commit a58a5d5ed00c1fb6cc0c3e42b9bbca863e36df15 and released in [v0.8.1](https://github.com/ruhley/angular-color-picker/releases/tag/v0.8.1)
