### ISSUE TITLE
[$compile:nonassign] Expression 'undefined' used with directive 'colorPicker' is non-assignable

### ISSUE THREAD

**Issue by kamilbrk** [ruhley/angular-color-picker#65]
Hi,

First of all, thanks for this amazing module, it is (and was even before v1) better solution than anything else I could have found for Angular.

I have two colour picker fields glued together with Bootstrap input-group and ui-bootstrap dropdowns to select the colour format.

![screen shot 2016-04-26 at 14 34 14](https://cloud.githubusercontent.com/assets/591349/14819872/feab4e12-0bbb-11e6-83e7-ccbbef3cd449.png)

Everything works just fine, but there's an Angular Non-Assignable Expression error in the console. The weird thing is, it only occurs when you select "hex" value from the dropdown. It does not throw any errors on the other two settings.

`angular.min.js:107 Error: [$compile:nonassign] http://errors.angularjs.org/1.4.9/$compile/nonassign?p0=undefined&p1=colorPicker`

I made a stripped down Plunker demo to aid investigation:
https://plnkr.co/edit/uc7cVQKeg5cCXVVsBmeG?p=preview

I've also tried to bind `color-picker-swatch-pos` and `color-picker-swatch-bootstrap` attributes to variables in a controller rather than using inline `'right'` and `false`. Same thing.

Any clue why does that happen? Am I misunderstanding something?

Chrome 50 & Chrome Canary 52, OS X 10.11.4

Cheers!

**Comment by ruhley** [comment]
The problem was that for hex format it was forcing `color-picker-alpha` to be false. Since Angular 1.4.9 I believe that you can't set a bound scope variable if it is not provided. I have fixed it by setting the bound declaraction to `=?`. This was the only place that a bound variable was directly set, so it should not happen again.

P.S. I don't know if you are doing this on your website, but in your example you are using rawgit.com, which isn't recommended. This library is now on [cdnjs](https://cdnjs.com/libraries/angularjs-color-picker) and I recommend you use that instead.

**Comment by ruhley** [comment]
Fixed in commit a4515c2c527f59f3bd78d1b9ead4868e8fb529e9 and released in [v1.0.6](https://github.com/ruhley/angular-color-picker/releases/tag/v1.0.6)

**Comment by kamilbrk** [comment]
Superb, works like a charm. Thank you!
